### ISSUE TITLE
Expand varyingSizeInputArray to be reusable/used multiple times in 1 page

### ISSUE THREAD

**Issue by MasterCoookie** [MasterCoookie/szychta-pl#60]

**Comment by MasterCoookie** [comment]
Done, will be merged with main soon.
Usage:

Import:
`<script type="module">
    import { initializeVaryingSizeInputArray } from '/js/varyingSizeInputArray.js';
    initializeVaryingSizeInputArray('links', 0, 8);
</script>`
![obraz](https://user-images.githubusercontent.com/49812285/235347656-fee764ff-6cee-480c-8a31-f010cffc3413.png)


HTML/ejs:
`
            <div class="col-sm-10" id="links-inputArray">
                
                <% if(applicant.links != null) { for(let i = 0; i < applicant.links.length; i++) { %>
                    <input value="<%= applicant.links[i] %>" class="links-array-input" type="text" id="links-input<%= i %>" />
                    <button type="button" class="links-array-remove" id="links-<%= i %>">x</button>
                <% }} %>
                <button id="links-arrayAdd">+</button>
            </div>`
![obraz](https://user-images.githubusercontent.com/49812285/235347673-fa406ca3-cb62-487a-b54a-51b5455f385d.png)

@macibol775 may interst u

**Comment by macibol775** [comment]
Fajne

**Comment by MasterCoookie** [comment]
No ejs html version:
`
        <div class="col-sm-10" id="keywords-inputArray">
            <div class="col-sm-10" id="keywords-inputArray">
                
                <button id="keywords-arrayAdd" style="display: inline;">+</button>
            </div>
        </div>`
![obraz](https://user-images.githubusercontent.com/49812285/235347876-30f58692-2765-47e9-8880-d0bd4288599b.png)

**Comment by MasterCoookie** [comment]
No ejs version:
` 
        <div class="col-sm-10" id="keywords-inputArray">
            
            <button id="keywords-arrayAdd" style="display: inline;">+</button>
        </div>`
![obraz](https://user-images.githubusercontent.com/49812285/235347928-abd5daf4-3b05-4eac-ba11-d4fca6823a90.png)
