### ISSUE TITLE
JobOffer view does not work after model change bagaloo

### ISSUE THREAD

**Issue by tomazaw** [MasterCoookie/szychta-pl#83]

**Comment by tomazaw** [comment]
/applicant/view/?id=64512e617b2e7d2e132d292b

**Comment by WojciechPtas** [comment]
This offer does not have a title, is this even allowed state for an offer? @tomazaw @MasterCoookie

**Comment by MasterCoookie** [comment]
It shouldn't, make sure to prevent it in model

**Comment by WojciechPtas** [comment]
Whats more, we dont have a db entry with that id XD

**Comment by WojciechPtas** [comment]
Actually it was mistake on our site, this job offer is perfectly valid
Fix on the way

**Comment by WojciechPtas** [comment]
@tomazaw  @MasterCoookie
